# Generated by Django 5.0.6 on 2024-05-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_type',
            field=models.CharField(choices=[('малой', 'Малой'), ('средней', 'Средней'), ('большой', 'Большой')], max_length=50),
        ),
    ]
