# Generated by Django 5.0.6 on 2024-05-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_statisticsreport_taxpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statisticsreport',
            name='report_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='taxpayment',
            name='payment_date',
            field=models.DateTimeField(),
        ),
    ]
