# Generated by Django 5.0.6 on 2024-05-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_statisticsreport_report_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.CharField(max_length=10)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('route', models.TextField()),
            ],
        ),
    ]
